### ISSUE TITLE
GET and POST stories

### ISSUE THREAD

**Issue by cmccoypdx** [gold-team-pdx/beautiful-portland#102]
Related to issue #96 

We need to store and retrieve stories created by Jenn in the database. Unique identifier should probably be timestamp. We also need to be able to differentiate between saved drafts and published stories.

**Comment by cmccoypdx** [comment]
![image1](https://user-images.githubusercontent.com/37560348/56443225-89f3e100-62a8-11e9-960c-fe7aafca94f1.jpeg)

**Comment by dgilmore** [comment]
I have finished the create new story front end and I think it will be good to implement the back end for each part of the story progression, not only for testing but for sanity.
