### ISSUE TITLE
Set up dev DB

### ISSUE THREAD

**Issue by cmccoypdx** [gold-team-pdx/beautiful-portland#12]
Set up a mongoDB instance for us to use in dev. Maybe populate with some test data.

**Comment by ronniesong0809** [comment]
I forgot to ask, there are two ways to setup the database instance, either mongodb-native or mongoose. any preference?

```node
// mongodb is the native driver
const MongoClient = require('mongodb').MongoClient;
...
query = {city: "Portland"}
db.collection("Volunteers").find(query, function (err, result) {
...
```
```node
// mongoose is object data modeling library for Mongodb and Nodejs (schema-based solution) 
const mongoose = require('mongoose');
const Schema = mongoose.Schema;
var VolunteerSchema = new Schema({ name: String, email: String, phone: Number});
```

https://mongoosejs.com/
https://stackoverflow.com/questions/28712248/difference-between-mongodb-and-mongoose
https://medium.com/chingu/an-overview-of-mongodb-mongoose-b980858a8994

**Comment by ronniesong0809** [comment]
![db](https://user-images.githubusercontent.com/6004123/53303109-661d9d00-381b-11e9-90ec-c1abd67ba526.png)
