### ISSUE TITLE
GET one/many stories

### ISSUE THREAD

**Issue by cmccoypdx** [gold-team-pdx/beautiful-portland#127]
We need an api request for populating the stories page with all of the most recent stories - we probably don't want to fetch ALL of the stories, and should instead have some limit on the amount pulled, and a button or other ui element to load more stories when the user scrolls down to the bottom.

We also need an ability to fetch just a single story for reading - maybe this can be one GET request with a param for one vs many stories.

**Comment by cmccoypdx** [comment]
We also need to figure out a way to handle retrieving the image for each story from the s3 bucket - may become separate task.

**Comment by dgilmore** [comment]
Ronnie opened a sort of redundant issue for specifically retrieving photos and the backend endpoint already written for retrieving the story text on the admin side will work for the public side as well.
