### ISSUE TITLE
Send email to volunteers when event is cancelled

### ISSUE THREAD

**Issue by cmccoypdx** [gold-team-pdx/beautiful-portland#163]
It would be nice if our app could send an automated email to all volunteers who are signed up for an event when that event gets cancelled. We don't necessarily have a clear idea of how to implement this yet, or how difficult/error prone it might be.

**Comment by dgilmore** [comment]
This stretch goal will not be met, but Will got creative with a work around to easily display all volunteer emails for a given event, making it easy to copy into an email client.
