### ISSUE TITLE
Blank screen on edit story submit

### ISSUE THREAD

**Issue by dgilmore** [gold-team-pdx/beautiful-portland#199]
when trying to save a story from the edit view, the screen goes blank after the modal click 'ok' and stays blank, never refreshes. Page reloads on browser refresh.

**Comment by Waschmid** [comment]
Ok, I think I solved this. Was an issue with the rich text editor I put in, somehow its value was getting turned into a string when it needs to stay an object. PR with the fix incoming, just want to a bit more testing.
