### ISSUE TITLE
Attempt to start up entire app

### ISSUE THREAD

**Issue by cmccoypdx** [gold-team-pdx/beautiful-portland#21]
We should be at the point now where it is possible to get all the basic elements of the app (backend, frontend, and database) up and running. Each of us should attempt this locally by running "yarn start" from the root of the project (make sure you've done a git pull and yarn bootstrap first). Document any problems in discord.

**Comment by cmccoypdx** [comment]
Seems to work ok for me

**Comment by dgilmore** [comment]
works for me too

**Comment by ronniesong0809** [comment]
it works perfectly well

**Comment by Eduardo-Robles7** [comment]
Works for me as well

**Comment by pholbert** [comment]
It's working for me

**Comment by babileej** [comment]
it works for me!

**Comment by Waschmid** [comment]
working a-ok for me
