### ISSUE TITLE
Fill form based on GET request

### ISSUE THREAD

**Issue by cmccoypdx** [gold-team-pdx/beautiful-portland#25]
Make a GET request to get the required sign-up categories for a given event, and use this to fill out the generic category components of a sign-up form for that event.

**Comment by dgilmore** [comment]
It seems like we need a HTTP client dependency for this issue? Here are a couple I have found:
https://github.com/axios/axios
https://alligator.io/js/fetch-api/

**Comment by Eduardo-Robles7** [comment]
@dgilmore I was going to ask this last meeting but forgot. I think those are some good options DJ, personally I have used axios in the past and found it well supported.

**Comment by babileej** [comment]
I have also used axios in the past and felt the same as eduardo.

**Comment by dgilmore** [comment]
yeah seems like axios is the favorite online too

**Comment by ronniesong0809** [comment]
i've never used axios before, but im willing to learn

**Comment by Waschmid** [comment]
For this task, the GET request handler from issue #40 on the backend will need to be updated to also include the max # of servings for any category (which is 150 for right now) in the response sent to the front end. Our current test data will need to be updated to include this field as well. (see issue #75 for details on the 'master' event document that will be the template for all events)

On the front end, logic needs to be added to block users from signing up for categories that are already full, and a message should be rendered letting them know as much.
