### ISSUE TITLE
Decide on structure of sign-up in DB

### ISSUE THREAD

**Issue by cmccoypdx** [gold-team-pdx/beautiful-portland#26]
Decide what exactly should go in a POST from a sign-up submission, and how that should look going into the database.

**Comment by Waschmid** [comment]
I uploaded an event.json file to the google drive in the 'Reference' folder as an example of the data model for an event. Of course, a real one would have more categories to reflect the signup sheet from the sponsors. 

The simplicity of using embedded documej'nts seemed too good to pass up, and nothing I found while researching led me to believe it'll nosedive performance or anything. As for in the db instance itself, I'm imagining we'll have a collection called 'events' where each event is a document.

**Comment by ronniesong0809** [comment]
@Waschmid i was trying to apply your method that having a single collection called 'events' where each event is a document, however, its seem like these fields of document will be difficulty to get tracking and update.
![image](https://user-images.githubusercontent.com/6004123/54050467-1c767000-4194-11e9-9c1e-5eb4edc0daaf.png)
![image](https://user-images.githubusercontent.com/6004123/54050478-25674180-4194-11e9-9e49-5dfd54668b3b.png)
![image](https://user-images.githubusercontent.com/6004123/54050606-7aa35300-4194-11e9-8cf2-26f245cd9dfa.png)

I'm wondering if this is a good idea that (please correct me)
each event is a collection (associate with the date of the event) under "events" databse:
![image](https://user-images.githubusercontent.com/6004123/54049327-07e4a880-4191-11e9-83ae-e48f4c0e2daf.png)

each signup is a document under a collection of associate date:
![image](https://user-images.githubusercontent.com/6004123/54049342-116e1080-4191-11e9-811d-5a4a75f448bd.png)

**Comment by Waschmid** [comment]
I was imagining each event being a document, but the categories and submissions would be embedded documents/arrays within that document. Are you saying that is where you think we'll run into issues tracking/updating? I added a document to the db more in the style of what I was thinking for reference.

**Comment by ronniesong0809** [comment]
> I was imagining each event being a document, but the categories and submissions would be embedded documents/arrays within that document. Are you saying that is where you think we'll run into issues tracking/updating? I added a document to the db more in the style of what I was thinking for reference.

oh, i see what you saying. sorry for misunderstanding, yeah this would be much better approach
![image](https://user-images.githubusercontent.com/6004123/54053007-d1139000-419a-11e9-90cb-cbec541d5578.png)

**Comment by Waschmid** [comment]
Just to be clear, I was intending on explicitly embedding the objects for categories/submissions into the event document, not using ObjectId references like the image you posted has. This way, we can take advantage of atomic transactions on the document file (the event) when adding/removing submissions. 

I'm not going to be available for the rest of today really, but I'll be online tomorrow morning through afternoon if you want to talk on discord just to really make sure we're on the same page regarding the db design.

**Comment by ronniesong0809** [comment]
i saw your sample on the MongoDB, I think i finally understand what you are saying. i didn't realized that we are able to embedding sub-documents as array object of the categories or submissions into the "event" document
![image](https://user-images.githubusercontent.com/6004123/54057241-3f5e4f80-41a7-11e9-9811-92fefa7285e6.png)
![image](https://user-images.githubusercontent.com/6004123/54074312-e1347980-4245-11e9-9cd9-e123bd69fb9b.png)
