### ISSUE TITLE
Create s3 bucket on docker container

### ISSUE THREAD

**Issue by cmccoypdx** [gold-team-pdx/beautiful-portland#33]
Now that we have an s3 capable docker container that runs alongside our dev build, we need to actually create the s3 bucket on it. This should be done via a script - preferably idempotent so that it can be run with our start scripts.

**Comment by Waschmid** [comment]
Got everything installed and working after dealing with some sass from my distro.

**Comment by ronniesong0809** [comment]
Working great!

![image](https://user-images.githubusercontent.com/6004123/53760301-51728200-3e77-11e9-8e4c-afa05fb88aed.png)
![image](https://user-images.githubusercontent.com/6004123/53760575-1de42780-3e78-11e9-8483-3f2df84190b4.png)

**Comment by dgilmore** [comment]
working well for me
