### ISSUE TITLE
Add events to dashboard

### ISSUE THREAD

**Issue by cmccoypdx** [gold-team-pdx/beautiful-portland#93]
Admins should be able to add events from the admin dashboard. Create a form for new events with fields for date, coordinator name, phone #, time.

**Comment by Waschmid** [comment]
Pic from 4/16 meeting: 
![image](https://user-images.githubusercontent.com/26891896/56307099-f3cd8880-60f8-11e9-9196-e088260052f6.png)

Handwriting translation:
The first row of fields are dropdowns to specify a date, these are followed by the coordinator name and phone # (text inputs), and then a dropdown to select the time (have selections for every hour or half hour maybe?). Then a big ol "MAKE EVENT" button.
