### ISSUE TITLE
Upcoming events

### ISSUE THREAD

**Issue by cmccoypdx** [gold-team-pdx/beautiful-portland#95]
Another admin dashboard view that will display upcoming events, and have some way to get details about each event. Possibly a list of dates that are clickable, and show the details for that date (EventList component) when clicked. Possibly some high-level information such as number signed up visible next to the date without clicking.

**Comment by Waschmid** [comment]
Pics from 4/16 meeting:
![image](https://user-images.githubusercontent.com/26891896/56307760-7b67c700-60fa-11e9-8a40-a772f039dbd6.png)
![image](https://user-images.githubusercontent.com/26891896/56307862-b5d16400-60fa-11e9-866d-22606408f0aa.png)


The "today->" is just indicating the most recent event should be on top, with future events descending from there. Each row is a link, that when clicked should take admin to a page represented by the second pic.
